### ISSUE TITLE
189邮箱报错

### ISSUE THREAD

**Issue by 76892881** [yuxian158/check#3]
Traceback (most recent call last):
  File "yuxian158_check_ck_cloud189.py", line 155, in <module>
    start()
  File "yuxian158_check_ck_cloud189.py", line 149, in start
    res = Cloud189CheckIn(check_item=_check_item).main()
  File "yuxian158_check_ck_cloud189.py", line 135, in main
    flag = self.login(session=session, username=cloud189_phone, password=cloud189_password)
  File "yuxian158_check_ck_cloud189.py", line 62, in login
    captchatoken = re.findall(r"captchaToken' value='(.+?)'", r.text)[0]
IndexError: list index out of range

**Comment by yuxian158** [comment]
貌似现在天翼网盘的签到函数都不可以用了，应该是官方改验证方式了，先删除了，等有了再添加
