### ISSUE TITLE
天翼云盘签到似乎不能用

### ISSUE THREAD

**Issue by synoman** [yuxian158/check#4]
运行日志如下

## 更新任务状态成功
尝试检查环境

成功 当前环境为青龙面板继续执行
已找到配置文件
Traceback (most recent call last):
  File "yuxian158_check_ck_cloud189.py", line 156, in <module>
    start()
  File "yuxian158_check_ck_cloud189.py", line 148, in start
    datas = json.loads(f.read())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
## 执行结束... 2021-08-02 14:48:23  耗时 9 秒

**Comment by yuxian158** [comment]
检查配置文件吧，注意不能用单引号

**Comment by synoman** [comment]
配置文件拉下来之后什么都没有改动，就是加了天翼云盘的账号密码而已

**Comment by yuxian158** [comment]
更新试一下
