### ISSUE TITLE
爱奇艺签到报错

### ISSUE THREAD

**Issue by cat-kun** [yuxian158/check#9]
>
## 开始执行... 2021-11-15 15:15:37

尝试检查环境

成功 当前环境为青龙面板继续执行
已找到配置文件
Traceback (most recent call last):
  File "yuxian158_check_ck_iqiyi.py", line 219, in <module>
    start()
  File "yuxian158_check_ck_iqiyi.py", line 213, in start
    res = IQIYICheckIn(check_item=_check_item).main()
  File "yuxian158_check_ck_iqiyi.py", line 177, in main
    p00001, p00002, p00003 = self.parse_cookie(self.check_item.get("iqiyi_cookie"))
  File "yuxian158_check_ck_iqiyi.py", line 23, in parse_cookie
    p00001 = re.findall(r"P00001=(.*?);", cookie)[0]
IndexError: list index out of range

## 执行结束... 2021-11-15 15:15:37 耗时 0 秒

爱奇艺cookie已配置

**Comment by qi-Inori** [comment]
ME TOO
